name: Automatisation des tests
on: push

jobs:
  compilation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Compilation
        run: |
          mkdir build
          cd build
          cmake ..
          make

  tests:
    runs-on: ubuntu-latest
    needs: compilation
    strategy:
      matrix:
        test_name: [add, sub, mul, div, car]

    steps:
      - uses: actions/checkout@v3

      - name: Run test ${{ matrix.test_name }}
        run: |
          mkdir build
          cd build
          cmake ..
          make
          ./src/calculator ${{ matrix.test_name }} 10 5

  deployment:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Deployment
        run: echo "Déploiement terminé !"
